#|这是一个多行注释测试块
1+1=2，而我写不完作业|#
(define x (matrix-set `(1 2 3) `(4 5 6)))
(define y (matrix-set `(7 8 9) `(10 11 12)))
(print "x= " x)
(print "y= " y)
(define x+y (+ x y))
(print "x+y= " x+y)
(define x-y (- x y))
(print "x-y= " x-y)
(print "-y= " (- y))
(define z (matrix-set `(4) `(5) `(6)))
(print "z= " z)
(define x*z (* x z))
(print "x*z= " x*z)
(define x*3*z (* x 3 z))
(print "x*3*z= " x*3*z)
(define x@z (@ x z))
(print "x@z= " x@z)
(define xT (T x))
(print "xT= " xT)
(define xTx (@ (T x) x))
(print "xTx= " xTx)
(define k (matrix-set `(1 2) `(4 5)))
(print "k= " k)
(define detk (det k))
(print "detk= " detk)
(define invk (inverse k))
(print "invk= " invk)